import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
  src: "../../public/gopher.otf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={myFont.className}>
      <body>{children}</body>
    </html>
  );
}
